export type Source = 'telemetry'|'measurement'|'catalog'|'engineer_override'|'customer_stated'|'report'|'text_extraction'|'assumption'|'default'|string
export interface Tracked<T = unknown> { value:T; unit?:string|null; source:Source; confidence:number; extracted_from?:string|null; source_document_ref?:string|null; note?:string|null; assumption?: { basis:string; bias:string; rationale:string; unbiased_value?:unknown|null; scenario_swept?:boolean }|null }
export interface CaseData { metadata?: { case_id?:string; well_name?:string; field_name?:string; raw_request?:string; data_access_level?:string }; task_type?:string; expectations?:Record<string, Tracked|unknown>; constraints?:Record<string, unknown>; complications?: {items?: Array<{type:string; severity?:string; evidence?:Tracked; quantity?:Tracked; quantity_unit?:string}>}; geometry?:Record<string, unknown>; fluid?:Record<string, Tracked|unknown>; reservoir?:Record<string, Tracked|unknown>; trajectory?:{horizon_months?:number} }
export interface Cell { month:number; envelope?:string; liquid_rate_bpd:number; head_developed_ft:number; head_required_ft:number; zone:string; q_over_qbep:number; efficiency_frac:number; pip_psi:number; motor_loading_frac?:number|null; shaft_hp_utilization?:number|null; shaft_nameplate_utilization?:number|null; shaft_nameplate_check_possible?:boolean; shaft_fracture_risk?:boolean; motor_nameplate_hp?:number|null; shaft_hp_operating_load?:number|null; cooling_velocity_ft_s?:number|null; cooling_verdict?:string|null; cooling_floor_applied_ft_s?:number|null; cooling_floor_basis?:string|null; cooling_upper_bound_checked?:boolean; }
export interface VSDPoint {month:number;frequency_hz:number;head_developed_ft:number;head_required_ft:number;motor_loading_frac:number;cable_voltage_drop_frac:number;motor_winding_temp_f:number;cable_conductor_temp_f:number}
export interface ToleranceFinding { channel:string; effect:string; band_frac:number; at_month?:number|null; flip_at_frac?:number|null; detail:string }
export interface ToleranceAssessment { pump_id:string; standard:string; curve_basis:string; band_applied:boolean; test_report_recommended:boolean; findings:ToleranceFinding[]; disclosures:string[]; recommendation:string }
export interface RankingStability { assessed:boolean; stable?:boolean|null; score_gap?:number|null; induced_swing?:number|null; tie_tolerance:number; detail:string }
export interface MotorSelfHeating { fluid_temp_f:number; rise_f:number; winding_temp_f:number; reference_rise_f:number; load_factor:number; velocity_factor:number; efficiency_factor:number; gas_factor:number; efficiency_basis:string }
export interface CableSelfHeating { fluid_temp_f:number; rise_f:number; conductor_temp_f:number; reference_rise_f:number; current_factor:number; velocity_factor:number; resistance_factor:number; fluid_factor:number }
export interface OperatingCurrent { operating_amps:number; full_load_amps:number; load_fraction:number; magnetizing_amps:number; load_amps:number; apparent_power_factor:number; linear_reference_amps:number; basis:string }
export interface Candidate { rank:number; configuration:{config_id:string; pump_id?:string; pump_model:string; manufacturer?:string; series:number; stages:number; frequency_hz:number; setting_depth_md_ft:number; motor_hp?:number|null; motor_id?:string|null; cable_awg?:string|null; cable_id?:string|null; gas_handling_id?:string|null; gas_handling_type?:string|null; seal_id?:string|null}; score:{total_score:number; objective:string; time_coverage_frac:number; bep_time_frac:number; efficiency_avg_frac:number; envelope_robustness:number; explanation?:string}; validity:{valid_until_months?:number|null; valid_until_months_min?:number|null; valid_until_months_max?:number|null; limiting_mechanism:string; limiting_zone?:string|null; valid_through_horizon?:boolean; horizon_months:number}; vsd_recovery?:{vsd_available:boolean; assessment?:'verified'|'not_needed'|'no_recovery'|'unverified'; verified_points?:VSDPoint[]; frequency_band_hz?:[number,number]|null; extended_validity_months?:number|null; recovered_horizon_frac?:number|null; frequency_schedule?:[number,number][]; note?:string|null}|null; timeline:Array<{month:number;label:string;zone:string;zone_description:string;q_over_qbep:number;severity:number;flagged:boolean;rate_bpd:number;pip_psi:number;efficiency_frac:number;note?:string|null}>; design_point:Cell; cells_sampled:Cell[]; soft_violations?:Array<{constraint_type:string;rigidity:string;message:string;actual_value?:number;limit_value?:number;unit?:string;remedy_hint?:string}>; warnings?:string[]; depends_on_estimated_catalog_data?:boolean; shaft_fracture_risk?:boolean; shaft_nameplate_check_performed?:boolean; cooling_verdict?:string|null; cooling_velocity_ft_s?:number|null; cooling_floor_applied_ft_s?:number|null; cooling_upper_bound_checked?:boolean; self_heating?:MotorSelfHeating|null; cable_self_heating?:CableSelfHeating|null; motor_operating_current?:OperatingCurrent|null; string_summary?:string|null; tolerance?:ToleranceAssessment|null }
export interface DesignData { design_id:string; case_id:string; verdict:string; verdict_explanation:string; branch:string; branch_rationale:string; candidates:Candidate[]; rejected:Array<{configuration:{pump_model:string;stages:number;frequency_hz:number};stage_rejected:string;reason:string;remedy_hints?:string[]}>; rejection_summary:Record<string,number>; scenario_points?:unknown[]; assumption_ledger:Array<{field_path:string;value:string;unit?:string|null;source:string;confidence:number;basis?:string|null;bias?:string|null;rationale?:string|null;unbiased_value?:string|null;materiality:string;sensitivity_note?:string|null}>; trust_register?:Array<{field_path:string;value:string;unit?:string|null;data_class:string;source:string;confidence:number;accuracy_owner:string;transcription_owned_by_system?:boolean;boundary_note?:string|null}>; responsibility_boundary_crossings?:string[]; blocking_data_gaps?:string[]; recommended_data_requests?:string[]; input_confidence:number; uses_estimated_catalog_data:boolean; uses_operator_supplied_motor_data?:boolean; has_nameplate_amps_conflict?:boolean; requires_magnet_thermal_verification?:boolean; has_shaft_fracture_risk?:boolean; provenance:{case_hash:string;config_hash:string;catalog_version:string;engine_version:string;computed_at?:string;compute_ms?:number;cells_evaluated?:number;configs_enumerated?:number;configs_surviving?:number}; judgments:Array<{judgment_id:string;statement:string;kind:string;references_facts:string[];confidence:number;confidence_basis:string;supporting_rule_ids?:string[];severity:string}>; engine_warnings?:string[]; ranking_stability?:RankingStability|null }
export interface Rule { rule_id:string; statement:string; evidence:{n_observations:number;n_distinct_fields:number;n_distinct_regions:number;effect_risk_ratio?:number|null;risk_difference_ci_95_low?:number;risk_difference_ci_95_high?:number;confidence_basis:string;warnings?:string[];evidence_strength:number}; bias_flags?:string[]; bias_explanations?:Record<string,string>; survival_summary?:Record<string,unknown>|null }
export interface PumpCurvePoint { q_bpd:number; head_ft_per_stage:number; head_ft_total:number; efficiency_frac:number; bhp_per_stage:number; bhp_total:number }
export interface PumpCurve { perimeter:string; perimeter_level:string; pump_id:string; pump_model:string; manufacturer:string; catalog_version:string; frequency_hz:number; reference_frequency_hz:number; stages:number; bep_q_bpd:number; q_min_bpd:number; q_max_bpd:number; recommended_min_bpd:number; recommended_max_bpd:number; downthrust_limit_bpd:number; upthrust_limit_bpd:number; data_quality:string; is_estimated:boolean; frequency_curve_method:string; caveats:string[]; points:PumpCurvePoint[] }
export interface KaplanMeierPoint { time_days:number; n_at_risk:number; n_events:number; n_censored:number; survival_probability:number; greenwood_variance:number|null; ci_95_lower:number|null; ci_95_upper:number|null }
export interface KaplanMeierEstimate { n_observations:number; n_failures:number; n_right_censored:number; points:KaplanMeierPoint[]; warnings:string[] }
export interface SurvivalResponse { perimeter:string; perimeter_level:string; pump_model:string|null; n_observations:number; estimate:KaplanMeierEstimate|null; explanation?:string }

export interface EgressChannel { channel:string; endpoint:string|null; endpoint_host?:string|null; resolved_address?:string|null; endpoint_location?:string; crosses_perimeter?:boolean; client:string; what_is_sent:string; consequence:string }
export interface Deployment {
  perimeter_model:{ levels:number; shape:string; outer:string; inner:string; sibling_operators_never_merge:boolean; framework_sections:string[] }
  caller:{ perimeter:string; perimeter_level:string; org_id:string; operator_id:string|null }
  storage:{ per_perimeter_physical_stores:boolean; storage_root:string|null; in_memory:boolean; store_for_caller:string; isolation_mechanism:string; second_mechanism:string }
  // §9.7 fields (declared_mode, effective_mode, endpoint_location, ...) are
  // optional because a customer running an older backend still needs the page
  // to render. New posture claims render only when the backend actually made
  // them; the frontend never fabricates a claim the backend did not send.
  agentic_layer:{ enabled:boolean; model_client:string|null; model_endpoint:string|null; severable:boolean; note:string; declared_mode?:string|null; effective_mode?:string; endpoint_location?:string; endpoint_host?:string|null; resolved_address?:string|null; inside_perimeter_override_applied?:boolean; posture_contradiction?:boolean; posture_contradiction_reason?:string|null; config_env_surface?:{name:string;purpose:string}[] }
  network_egress_from_design_path:boolean
  egress_channels:EgressChannel[]
  // §9.7. Optional because an older backend will not send it, and rendering a
  // hardcoded "no browser egress" panel against a backend that never made the
  // claim would be the frontend asserting a security property on its own.
  browser_egress?:{ third_party_requests:boolean; fonts:string; analytics_or_error_reporting:string|null; verified_by:string; enforcement:string }
  leaves_the_perimeter:string[]
  vendor_access:string
  crossing_a_boundary:string
}
export interface Cell { converged?:boolean; total_fluid_intake_bpd?:number }
